title: Co-op Reports
description: A collection of work-term reports written by me, Ben Rottke.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions
repository: Xairos/Co-op-Reports
